// JsFromRoutes CacheKey 13466c777840387498fb0240f4b1d6f9
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/language_services'),
  create: /* #__PURE__ */ definePathHelper('post', '/language_services'),
  new: /* #__PURE__ */ definePathHelper('get', '/language_services/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/language_services/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/language_services/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/language_services/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/language_services/:id'),
}
